version: '3.3'
services:

  cassandra:
    image: bitnami/cassandra:latest
    ports:
      - '7000:7000'
      - '7001:7001'
      - '9042:9042'
      - '9160:9160'
    volumes:
      - cassandra_data:/bitnami

volumes:
  cassandra_data:
    driver: local